default:
  graceTimeOut: 100
  readTimeout: 100
  idleTimeout: 100
  writeTimeout: 100
  maxHeaderBytes: 10000
  readHeaderTimeout: 200

frontends:
- name: account
  address: localhost:8080
  # certificate: /Users/aapeli/labchan/ssl/account.pem
  # certificateKey: /Users/aapeli/labchan/ssl/account-key.pem
  virtualHosts:
    - domains: ["localhost"]
      filters:
      - name: cors
        config:
          allowHeaders: "Content-Type, Authorization"
          allowOrigin: "*"
          allowMethods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
      rules:
      - name: account
        locationRegexp: ^/v1/account/(.*)
        matchMethods: [GET,POST,PUT,DELETE,PATCH]
        rewitePath: /$1
        backend: account
        # filters:
        # - name: accessByAccount
        #   config:
        #     serverName: account
        #     address: 127.0.0.1:8082
        #     certificate: /Users/aapeli/labchan/ssl/ca.pem

backends:
- name: account
  balance: roundrobin
  servers:
  - name: account1
    weight: 2
    failTimeout: 10
    maxFails: 2
    tcpTimeout: 100
    tcpKeepAlive: 100
    idleConnTimeout: 100
    maxIdleConnsPerHost: 100
    target: https://127.0.0.1:8083/

